apiVersion: v1
kind: ConfigMap
metadata:
  name: genomex-config
  namespace: genomex
data:
  NODE_ENV: "production"
  PORT: "5000"
  LOG_LEVEL: "info"
  JWT_EXPIRY: "24h"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "genomexdb"
  DB_USER: "genomex"
